# Generated by Django 5.2.1 on 2025-06-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['name'], 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name_plural': 'Species'},
        ),
        migrations.RemoveField(
            model_name='species',
            name='image',
        ),
        migrations.AlterField(
            model_name='family',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='iucn_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(max_length=100),
        ),
    ]
