# Generated by Django 5.2.1 on 2025-06-07 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0002_alter_family_options_alter_species_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['common_name'], 'verbose_name_plural': 'Species'},
        ),
        migrations.RenameField(
            model_name='species',
            old_name='name',
            new_name='common_name',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='iucn_status',
            new_name='conservation_status',
        ),
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='birddetection',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bird_detections', to='admindashboard.site'),
        ),
    ]
