# Generated by Django 5.2.1 on 2025-06-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0003_site_alter_species_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='species_images/'),
        ),
    ]
