# Generated by Django 5.2.1 on 2025-06-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0004_species_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bird_images/'),
        ),
    ]
