# Generated by Django 5.2.1 on 2025-06-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0005_alter_species_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='code',
        ),
    ]
