# Generated by Django 5.2.1 on 2025-06-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0007_add_initial_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='birddetection',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='birddetection',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='birddetection',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='birddetection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='detection_images/'),
        ),
    ]
