# Generated by Django 5.2.1 on 2025-06-08 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0008_birddetection_count_alter_birddetection_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StagedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='staging/')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='staged', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_data', models.JSONField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
    ]
