# Generated by Django 5.2.1 on 2025-06-09 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0009_stagedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StagedImage',
        ),
    ]
