# Generated by Django 5.1.7 on 2025-04-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadminloginapp', '0002_user_password_changed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_changed_at',
        ),
    ]
