# Generated by Django 5.1.7 on 2025-04-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadminloginapp', '0003_remove_user_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
