# Generated by Django 5.2.1 on 2025-06-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardadminapp', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('field_worker', 'Field Worker')], default='field_worker', max_length=20),
        ),
    ]
