# Generated by Django 5.1.7 on 2025-04-02 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardadminapp', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='middle_name',
        ),
    ]
