# Generated by Django 5.1.7 on 2025-03-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardadminapp', '0002_remove_userprofile_is_active_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Field Worker', 'Field Worker'), ('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], max_length=50),
        ),
    ]
