# Generated by Django 5.1.7 on 2025-03-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardadminapp', '0003_userprofile_is_active_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='jepoyinere2003@gmail.com', max_length=254, unique=True),
        ),
    ]
