# Generated by Django 5.2.1 on 2025-06-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardadminapp', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('field_worker', 'Field Worker')], max_length=20, unique=True)),
                ('view_report_management', models.BooleanField(default=True)),
                ('view_species_management', models.BooleanField(default=True)),
                ('view_site_management', models.BooleanField(default=True)),
                ('view_bird_census_management', models.BooleanField(default=True)),
                ('view_image_processing', models.BooleanField(default=True)),
                ('generate_reports', models.BooleanField(default=True)),
                ('modify_data', models.BooleanField(default=True)),
                ('add_sites', models.BooleanField(default=True)),
                ('add_birds', models.BooleanField(default=True)),
                ('generate_data', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Permission Setting',
                'verbose_name_plural': 'Permission Settings',
            },
        ),
    ]
