# Generated by Django 5.1.7 on 2025-04-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardadminapp', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='custom_user_id',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
