# Generated by Django 5.2.1 on 2025-06-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardadminapp', '0006_permissionsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-timestamp'], 'verbose_name': 'System Log', 'verbose_name_plural': 'System Logs'},
        ),
        migrations.RemoveField(
            model_name='log',
            name='event',
        ),
        migrations.AddField(
            model_name='log',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='event_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Creation'), ('update', 'Update'), ('permission', 'Permission Change'), ('delete', 'Deletion')], default='login', max_length=20),
        ),
        migrations.AddField(
            model_name='log',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10),
        ),
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionsetting',
            name='view_logs',
            field=models.BooleanField(default=True),
        ),
    ]
